name: Android CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: recursive
          fetch-depth: 0

    - name: Set-up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: gradle build

    - name: Sign App APK
      uses: ilharp/sign-android-release@nightly
      id: sign_webapp
      with:
        releaseDir: webapp/build/outputs/apk/release
        signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
        keyAlias: mfuns-rev0
        keyStorePassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Push Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mfuns-webapp-${{ github.sha }}
        path: ${{steps.sign_webapp.outputs.signedFile}}
