name: Android CI

on:
  [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive
          fetch-depth: 0
    - name: Set-up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: gradle build

    - name: Sign App APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ fromJson(secrets.ANDROID_KEY).key }}
        alias: ${{ fromJson(secrets.ANDROID_KEY).alias }}
        keyStorePassword: ${{ fromJson(secrets.ANDROID_KEY).password }}
        keyPassword: ${{ fromJson(secrets.ANDROID_KEY).password }}

    - name: Push Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mfuns-webapp-${{ github.sha }}
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
