name: Android CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive
          fetch-depth: 0

    - name: Set-up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: gradle assembleRelease

    - name: Sign App APK
      uses: ilharp/sign-android-release@nightly
      id: sign_app
      with:
        releaseDir: app/build/outputs/apk/release
        signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
        keyAlias: mfuns-rev0
        keyStorePassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Push Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mfuns-webapp-${{ github.sha }}
        path: ${{steps.sign_app.outputs.signedFile}}
